# This is a basic workflow to help you get started with Actions

name: if test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: exit 1
    
        
  job2:
   if: true
   runs-on: ubuntu-latest
   steps:
      - name: Run a one-line script
        run: echo Hello, world222!
   needs: [job1]
        
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world333!
    needs: [job2]
